import json
import os
from typing import Any, Dict, List, Optional, Set

# ---------------------------------------------------------------------------
# 1st-Round Draft Picks — names normalized to lowercase for intersection math
# ---------------------------------------------------------------------------
CANONICAL_ROUND_1_PICKS: Set[str] = {
    # 2026 Draft top & projected 1st rounders
    "arch manning", "nico iamaleava", "jeremiah smith", "ryan williams", "dylan stewart",
    "jordan seaton", "colin simmons", "ellis robinson iv", "ellis robinson", "garrett nussmeier",
    "conner weigman", "zachariah branch", "caleb downs", "eugene wilson iii", "eugene wilson",
    "peter woods", "francis mauigoa", "kadyn proctor", "rueben owens", "justice haynes",
    "nyck harbor", "dj lagway", "anthony hill jr", "carnell tate", "tj shanahan",
    "samson okunlola", "suntarine perkins", "peyton bowen", "adepoju adebawore", "damon wilson jr",
    "jordan hall", "daevin hobbs", "taurean york", "tony mitchell", "malik muhammad",
    "cormani mcclain", "jaylen mbakwe", "kj bolden", "sammy brown", "terry bussey",

    # 2025 Draft 1st round picks & top prospects
    "cam ward", "travis hunter", "shedeur sanders", "abdul carter", "ashton jeanty",
    "tetairoa mcmillan", "mason graham", "will campbell", "malaki starks", "kelvin banks jr",
    "kelvin banks", "james pearce jr", "james pearce", "tyler booker", "luther burden iii",
    "luther burden", "colston loveland", "mykel williams", "shavon revel jr", "shavon revel",
    "jalon walker", "kenneth grant", "nic scourton", "jalen milroe", "quinn ewers",
    "jaxson dart", "emeka egbuka", "isaiah bond", "treveyon henderson", "quinshon judkins",
    "jonah savaiinaea", "josh simmons", "benjamin morrison", "will johnson", "jack sawyer",
    "derrick harmon", "walter nolen", "jihaad campbell", "carson beck", "tyler warren",
    "aireontae ersery", "wyatt milum", "josh conerly jr", "josh conerly", "grey zabel",
    "matthew golden", "tre harris", "xavier restrepo", "jayden higgins", "omarion hampton",
    "kaleb johnson", "nicholas singleton", "princely umanmielen", "landon jackson", "mike green",
    "donovan ezeiruaku", "tj sanders", "t.j. sanders", "deone walker", "jahdae barron",
    "maxwell hairston", "tacario davis", "trey amos", "xavier watts", "andrew mukuba",
    "nick emmanwori", "kevin winston jr", "kevin winston", "lathan ransom", "cam skattebo",
    "harold fannin jr", "kyle monangai", "armand membou",

    # 2024 Draft 1st round picks
    "caleb williams", "jayden daniels", "drake maye", "marvin harrison jr", "marvin harrison",
    "joe alt", "malik nabers", "jc latham", "michael penix jr", "michael penix",
    "rome odunze", "jj mccarthy", "j.j. mccarthy", "olu fashanu", "olumuyiwa fashanu",
    "bo nix", "brock bowers", "taliese fuaga", "laiatu latu", "byron murphy ii",
    "dallas turner", "amarius mims", "jared verse", "troy fautanu", "chop robinson",
    "quinyon mitchell", "brian thomas jr", "terrion arnold", "jordan morgan", "graham barton",
    "darius robinson", "xavier worthy", "tyler guyton", "nate wiggins", "ricky pearsall",
    "xavier legette",

    # Modern & Historical 1st round picks
    "patrick mahomes", "aaron rodgers", "peyton manning", "eli manning", "dan marino",
    "john elway", "jim kelly", "terry bradshaw", "troy aikman", "cam newton",
    "matthew stafford", "joe burrow", "josh allen", "lamar jackson", "justin herbert",
    "trevor lawrence", "jordan love", "baker mayfield", "kyler murray", "tua tagovailoa",
    "jared goff", "cj stroud", "c.j. stroud", "carson palmer", "donovan mcnabb",
    "drew bledsoe", "joe flacco", "jay cutler", "sam darnold", "mark sanchez",
    "zach wilson", "michael vick", "daunte culpepper", "alex smith", "matt ryan",
    "philip rivers", "ben roethlisberger", "emmitt smith", "barry sanders", "walter payton",
    "adrian peterson", "christian mccaffrey", "ladainian tomlinson", "eric dickerson",
    "oj simpson", "o.j. simpson", "earl campbell", "marshall faulk", "jerome bettis",
    "tony dorsett", "marcus allen", "john riggins", "franco harris", "gale sayers",
    "marshawn lynch", "saquon barkley", "bijan robinson", "jahmyr gibbs", "shaun alexander",
    "edgerrin james", "jerry rice", "randy moss", "larry fitzgerald", "calvin johnson",
    "tim brown", "reggie wayne", "torry holt", "michael irvin", "james lofton",
    "julio jones", "deandre hopkins", "justin jefferson", "jamarr chase", "ja'marr chase",
    "ceedee lamb", "mike evans", "dj moore", "d.j. moore", "garrett wilson", "chris olave",
    "tony gonzalez", "greg olsen", "tj hockenson", "t.j. hockenson", "kyle pitts",
    "reggie white", "bruce smith", "lawrence taylor", "jj watt", "j.j. watt",
    "tj watt", "t.j. watt", "aaron donald", "von miller", "myles garrett",
    "nick bosa", "joey bosa", "micah parsons", "derrick thomas", "dwight freeney",
    "clay matthews", "julius peppers", "demarcus ware", "ndamukong suh", "quinnen williams",
    "ray lewis", "brian urlacher", "dick butkus", "junior seau", "luke kuechly",
    "patrick willis", "derrick brooks", "roquan smith", "deion sanders", "charles woodson",
    "rod woodson", "ed reed", "troy polamalu", "ronnie lott", "darrelle revis",
    "champ bailey", "steve atwater", "earl thomas", "patrick peterson", "jalen ramsey",
    "patrick surtain ii", "sauce gardner", "minkah fitzpatrick", "derwin james", "kyle hamilton",
    "kenny clark", "jaire alexander", "quay walker", "devonte wyatt", "rashan gary",
    "eric stokes", "darnell savage", "ha ha clinton-dix", "nick perry", "justin harrell",
    "aj hawk", "a.j. hawk", "jamal reynolds", "bubba franks", "antuan edwards",
    "vonnie holliday", "ross verba", "john michels", "craig newsome", "aaron taylor",
    "wayne simmons", "terrell buckley", "tony mandarich", "sterling sharpe",
    "will mcdonald iv", "jermaine johnson", "alijah vera-tucker", "mekhi becton",
    "jamal adams", "darron lee", "leonard williams", "calvin pryor", "dee milliner",
    "sheldon richardson", "quinton coples", "muhammad wilkerson", "kyle wilson",
    "dustin keller", "d'brickashaw ferguson", "nick mangold", "jonathan vilma",
    "bryan thomas", "santana moss", "chad pennington", "john abraham", "shaun ellis",
    "keyshawn johnson", "joe namath", "anthony richardson", "will levis", "mac jones",
    "justin fields", "trey lance", "dwayne haskins", "daniel jones", "josh rosen",
    "mitchell trubisky", "deshaun watson", "paxton lynch", "jameis winston", "marcus mariota",
    "blake bortles", "johnny manziel", "teddy bridgewater", "ej manuel", "andrew luck",
    "robert griffin iii", "ryan tannehill", "brandon weeden", "jake locker", "blaine gabbert",
    "christian ponder", "sam bradford", "tim tebow", "josh freeman", "jamarcus russell",
    "brady quinn", "vince young", "matt leinart", "jason campbell", "jp losman",
    "byron leftwich", "kyle boller", "rex grossman", "david carr", "joey harrington",
    "patrick ramsey", "tim couch", "akili smith", "cade mcnown", "ryan leaf",
    "jim druckenmiller", "kerry collins", "steve mcnair", "heath shuler", "trent dilfer",
    "rick mirer", "david klingler", "tommy maddox", "dan mcguire", "todd marinovich",
    "jeff george", "andre ware", "vinny testaverde", "kelly stouffer", "chris miller",
    "jim everett", "chuck long", "bernie kosar", "todd blackledge", "tony eason",
    "ken obrien", "art schlichter", "jim mcmahon", "rich campbell",
    # Additional notable 1st rounders
    "dez bryant", "odell beckham jr", "stefon diggs", "tyreek hill", "davante adams",
    "antonio brown", "amari cooper", "aj green", "a.j. green", "brandon marshall",
    "alshon jeffery", "sammy watkins", "mike williams", "cordarrelle patterson",
    "eric fisher", "luke joeckel", "blake ferguson", "trent richardson",
    "ryan mathews", "c.j. spiller", "c j spiller", "jahvid best", "demarco murray",
    "lesean mccoy", "le'veon bell", "leveon bell", "ezekiel elliott", "leonard fournette",
    "dalvin cook", "joe mixon", "zeke elliott", "nick chubb", "josh jacobs",
    "clyde edwards-helaire", "travis etienne", "najee harris", "breece hall",
    "bijan robinson", "jahmyr gibbs",
}

# ---------------------------------------------------------------------------
# Franchise Map — player name (lowercase) → list of franchise IDs
# ---------------------------------------------------------------------------
CANONICAL_FRANCHISE_MAP: Dict[str, List[str]] = {
    # ===== Green Bay Packers (GNB) =====
    "aaron rodgers": ["GNB", "NYJ"],
    "brett favre": ["ATL", "GNB", "NYJ", "MIN"],
    "jordan love": ["GNB"],
    "clay matthews": ["GNB", "LAR"],
    "kenny clark": ["GNB"],
    "jaire alexander": ["GNB"],
    "quay walker": ["GNB"],
    "jordan morgan": ["GNB"],
    "devonte wyatt": ["GNB"],
    "rashan gary": ["GNB"],
    "bart starr": ["GNB"],
    "reggie white": ["PHI", "GNB", "CAR"],
    "james lofton": ["GNB", "LVR", "BUF", "LAR", "PHI"],
    "charles woodson": ["LVR", "GNB"],
    "leroy butler": ["GNB"],
    "greg jennings": ["GNB", "MIN", "MIA"],
    "ryan longwell": ["GNB", "MIN"],
    "zadarius smith": ["BAL", "GNB", "MIN", "CLE", "DET"],
    "zarius smith": ["BAL", "GNB", "MIN", "CLE", "DET"],
    "darren sharper": ["GNB", "MIN", "NOR"],
    "davante adams": ["GNB", "LVR", "NYJ"],
    "aaron jones": ["GNB", "MIN"],
    "sterling sharpe": ["GNB"],
    "donald driver": ["GNB"],
    "jordy nelson": ["GNB", "LVR"],
    "randall cobb": ["GNB", "DAL", "HOU", "NYG"],
    "nick collins": ["GNB"],
    "aj hawk": ["GNB", "ATL", "CIN"],
    "a.j. hawk": ["GNB", "ATL", "CIN"],
    "ha ha clinton-dix": ["GNB", "WAS", "CHI", "DAL"],
    "darnell savage": ["GNB"],
    "eric stokes": ["GNB"],
    "christian watson": ["GNB"],
    "romeo doubs": ["GNB"],
    "luke musgrave": ["GNB"],
    "marshawn lynch": ["BUF", "SEA", "LVR"],  # not GNB

    # ===== New York Jets (NYJ) =====
    "sam darnold": ["NYJ", "CAR", "SFO", "MIN"],
    "joe namath": ["NYJ", "LAR"],
    "curtis martin": ["NWE", "NYJ"],
    "darrelle revis": ["NYJ", "TAM", "NWE", "KC"],
    "ronnie lott": ["SFO", "LVR", "NYJ"],
    "ed reed": ["BAL", "HOU", "NYJ"],
    "mark sanchez": ["NYJ", "PHI", "DAL", "WAS"],
    "zach wilson": ["NYJ", "DEN"],
    "quinnen williams": ["NYJ"],
    "sauce gardner": ["NYJ"],
    "garrett wilson": ["NYJ"],
    "breece hall": ["NYJ"],
    "olu fashanu": ["NYJ"],
    "alijah vera-tucker": ["NYJ"],
    "alijah vera tucker": ["NYJ"],
    "ryan fitzpatrick": ["LAR", "CIN", "BUF", "TEN", "HOU", "NYJ", "TAM", "MIA", "WAS"],
    "keyshawn johnson": ["NYJ", "TAM", "DAL", "CAR"],
    "wayne chrebet": ["NYJ"],
    "laveranues coles": ["NYJ", "WAS"],
    "chad pennington": ["NYJ", "MIA"],
    "d'brickashaw ferguson": ["NYJ"],
    "nick mangold": ["NYJ"],
    "leonard williams": ["NYJ", "NYG"],
    "jamal adams": ["NYJ", "SEA", "LAR"],
    "calvin pryor": ["NYJ"],
    "dee milliner": ["NYJ"],
    "will mcdonald iv": ["NYJ"],
    "jermaine johnson": ["NYJ"],
    "c.j. mosley": ["BAL", "NYJ"],
    "jamison crowder": ["WAS", "NYJ", "BUF"],
    "elijah moore": ["NYJ", "CLE"],
    "corey davis": ["TEN", "NYJ"],

    # ===== Minnesota Vikings (MIN) =====
    "dalvin cook": ["MIN", "NYJ", "BAL", "DAL"],
    "kirk cousins": ["WAS", "MIN", "ATL"],
    "daunte culpepper": ["MIN", "MIA", "LVR", "DET"],
    "warren moon": ["TEN", "MIN", "SEA", "KC"],
    "randy moss": ["MIN", "LVR", "NWE", "TEN", "SFO"],
    "cris carter": ["PHI", "MIN", "MIA"],
    "adrian peterson": ["MIN", "ARI", "NOR", "WAS", "DET", "TEN", "SEA"],
    "justin jefferson": ["MIN"],
    "jj mccarthy": ["MIN"],
    "j.j. mccarthy": ["MIN"],
    "dallas turner": ["MIN"],
    "jared allen": ["KC", "MIN", "CHI", "CAR"],
    "chad greenway": ["MIN"],
    "harrison smith": ["MIN"],
    "xavier rhodes": ["MIN", "IND", "ATL"],
    "stefon diggs": ["MIN", "BUF", "HOU"],
    "adam thielen": ["MIN", "CAR"],
    "kyle rudolph": ["MIN", "NYG"],
    "everson griffen": ["MIN", "DAL", "DET", "LVR"],
    "eric kendricks": ["MIN", "LAC"],
    "danielle hunter": ["MIN", "HOU"],
    "patrick peterson": ["ARI", "MIN", "PIT"],
    "fran tarkenton": ["MIN", "NYG"],
    "carl eller": ["MIN"],
    "alan page": ["MIN", "CHI"],
    "john randle": ["MIN", "SEA"],
    "paul krause": ["WAS", "MIN"],
    "mick tingelhoff": ["MIN"],
    "korey stringer": ["MIN"],
    "sam bradford": ["STL", "PHI", "MIN", "ARI"],
    "teddy bridgewater": ["MIN", "NOR", "DEN", "CAR", "MIA"],

    # ===== Kansas City Chiefs (KC) =====
    "patrick mahomes": ["KC"],
    "xavier worthy": ["KC"],
    "travis kelce": ["KC"],
    "tyreek hill": ["KC", "MIA"],
    "clyde edwards-helaire": ["KC"],
    "mecole hardman": ["KC", "NYJ"],
    "jerick mckinnon": ["MIN", "SFO", "KC"],
    "dee ford": ["KC", "SFO"],
    "frank clark": ["SEA", "KC"],
    "chris jones": ["KC"],
    "l'jarius sneed": ["KC", "TEN"],
    "juan thornhill": ["KC", "CLE"],
    "darrelle revis": ["NYJ", "TAM", "NWE", "KC"],
    "warren moon": ["TEN", "MIN", "SEA", "KC"],
    "jared allen": ["KC", "MIN", "CHI", "CAR"],
    "tony gonzalez": ["KC", "ATL"],
    "derrick thomas": ["KC"],
    "priest holmes": ["BAL", "KC"],
    "larry johnson": ["KC"],
    "jamaal charles": ["KC"],
    "len dawson": ["PIT", "CLE", "KC"],
    "will shields": ["KC"],
    "dontari poe": ["KC", "ATL", "CAR", "DAL"],

    # ===== Dallas Cowboys (DAL) =====
    "dak prescott": ["DAL"],
    "ceedee lamb": ["DAL"],
    "tyler guyton": ["DAL"],
    "trevon diggs": ["DAL"],
    "micah parsons": ["DAL"],
    "demarcus ware": ["DAL", "DEN"],
    "troy aikman": ["DAL"],
    "emmitt smith": ["DAL", "ARI"],
    "michael irvin": ["DAL"],
    "tony dorsett": ["DAL", "DEN"],
    "deion sanders": ["ATL", "SFO", "DAL", "WAS", "BAL"],
    "terrell owens": ["SFO", "PHI", "DAL", "BUF", "CIN"],
    "dez bryant": ["DAL"],
    "jason witten": ["DAL", "LVR", "LAR"],
    "larry allen": ["DAL", "SFO"],
    "darren woodson": ["DAL"],
    "ray lewis": ["BAL"],  # not DAL
    "mark sanchez": ["NYJ", "PHI", "DAL", "WAS"],
    "randall cobb": ["GNB", "DAL", "HOU", "NYG"],
    "amari cooper": ["LVR", "DAL", "CLE", "BUF"],
    "cedrick wilson": ["DAL", "MIA"],
    "leighton vander esch": ["DAL"],
    "ezekiel elliott": ["DAL", "NWE"],
    "tony romo": ["DAL"],
    "roger staubach": ["DAL"],
    "bob hayes": ["DAL"],
    "ed jones": ["DAL"],
    "randy white": ["DAL"],
    "charles haley": ["SFO", "DAL"],
    "jay novacek": ["STL", "DAL"],
    "moose johnston": ["DAL"],
    "rico gathers": ["DAL"],

    # ===== San Francisco 49ers (SFO) =====
    "brock purdy": ["SFO"],
    "ricky pearsall": ["SFO"],
    "nick bosa": ["SFO"],
    "fred warner": ["SFO"],
    "christian mccaffrey": ["CAR", "SFO"],
    "deebo samuel": ["SFO"],
    "george kittle": ["SFO"],
    "brandon aiyuk": ["SFO"],
    "jerry rice": ["SFO", "LVR", "SEA"],
    "joe montana": ["SFO", "KC"],
    "steve young": ["TAM", "SFO"],
    "ronnie lott": ["SFO", "LVR", "NYJ"],
    "terrell owens": ["SFO", "PHI", "DAL", "BUF", "CIN"],
    "charles haley": ["SFO", "DAL"],
    "dwight clark": ["SFO"],
    "john taylor": ["SFO"],
    "roger craig": ["SFO", "LVR", "MIN"],
    "tom rathman": ["SFO", "LVR"],
    "harris barton": ["SFO"],
    "trent williams": ["WAS", "SFO"],
    "patrick surtain ii": ["DEN"],  # not SFO
    "deion sanders": ["ATL", "SFO", "DAL", "WAS", "BAL"],
    "randy moss": ["MIN", "LVR", "NWE", "TEN", "SFO"],
    "sam darnold": ["NYJ", "CAR", "SFO", "MIN"],
    "dee ford": ["KC", "SFO"],
    "richard sherman": ["SEA", "SFO"],
    "eric reid": ["SFO", "CAR"],
    "navorro bowman": ["SFO"],
    "patrick willis": ["SFO"],
    "frank gore": ["SFO", "IND", "MIA", "BUF", "NYJ"],
    "marquise goodwin": ["SFO", "CHI", "PHI"],
    "kyle shanahan": [],  # coach not player

    # ===== Philadelphia Eagles (PHI) =====
    "jalen hurts": ["PHI"],
    "quinyon mitchell": ["PHI"],
    "aj brown": ["TEN", "PHI"],
    "devonta smith": ["PHI"],
    "dallas goedert": ["PHI"],
    "lane johnson": ["PHI"],
    "jason kelce": ["PHI"],
    "fletcher cox": ["PHI"],
    "haason reddick": ["ARI", "CAR", "PHI", "NYJ"],
    "james bradberry": ["CAR", "NYG", "PHI"],
    "darius slay": ["DET", "PHI"],
    "reggie white": ["PHI", "GNB", "CAR"],
    "donovan mcnabb": ["PHI", "WAS"],
    "cris carter": ["PHI", "MIN", "MIA"],
    "terrell owens": ["SFO", "PHI", "DAL", "BUF", "CIN"],
    "michael irvin": ["DAL"],  # not PHI
    "james lofton": ["GNB", "LVR", "BUF", "LAR", "PHI"],
    "mark sanchez": ["NYJ", "PHI", "DAL", "WAS"],
    "brian dawkins": ["PHI", "DEN"],
    "jeremiah trotter": ["PHI", "WAS", "TAM"],
    "corey simon": ["PHI"],
    "sam bradford": ["STL", "PHI", "MIN", "ARI"],
    "donovan mcnabb": ["PHI", "WAS"],
    "desean jackson": ["PHI", "WAS", "TAM", "LAR"],
    "lesean mccoy": ["PHI", "BUF", "KC", "TAM"],
    "darren sproles": ["LAC", "NOR", "PHI"],
    "zach ertz": ["PHI", "ARI"],
    "jordan matthews": ["PHI", "BUF"],
    "jordan howard": ["CHI", "PHI", "MIA"],
    "carson wentz": ["PHI", "IND", "WAS"],

    # ===== Pittsburgh Steelers (PIT) =====
    "troy fautanu": ["PIT"],
    "t.j. watt": ["PIT"],
    "tj watt": ["PIT"],
    "minkah fitzpatrick": ["MIA", "PIT"],
    "najee harris": ["PIT"],
    "pat freiermuth": ["PIT"],
    "diontae johnson": ["PIT", "CAR", "BAL"],
    "kenny pickett": ["PIT"],
    "ben roethlisberger": ["PIT"],
    "antonio brown": ["PIT", "LVR", "TAM"],
    "le'veon bell": ["PIT", "NYJ", "KC"],
    "leveon bell": ["PIT", "NYJ", "KC"],
    "ryan shazier": ["PIT"],
    "james harrison": ["PIT", "CIN", "BAL"],
    "troy polamalu": ["PIT"],
    "hines ward": ["PIT"],
    "jerome bettis": ["LAR", "PIT"],
    "franco harris": ["PIT", "SEA"],
    "terry bradshaw": ["PIT"],
    "mel blount": ["PIT"],
    "jack ham": ["PIT"],
    "jack lambert": ["PIT"],
    "lynn swann": ["PIT"],
    "john stallworth": ["PIT"],
    "mike webster": ["PIT", "KC"],
    "casey hampton": ["PIT"],
    "james farrior": ["NYJ", "PIT"],
    "lamarr woodley": ["PIT", "ARI"],
    "mike tomlin": [],  # coach

    # ===== New England Patriots (NWE) =====
    "drake maye": ["NWE"],
    "tom brady": ["NWE", "TAM"],
    "randy moss": ["MIN", "LVR", "NWE", "TEN", "SFO"],
    "darrelle revis": ["NYJ", "TAM", "NWE", "KC"],
    "rob gronkowski": ["NWE", "TAM"],
    "julian edelman": ["NWE"],
    "wes welker": ["MIA", "NWE", "DEN"],
    "danny amendola": ["LAR", "NWE", "MIA", "PHI"],
    "deion branch": ["NWE", "SEA"],
    "curtis martin": ["NWE", "NYJ"],
    "corey dillon": ["CIN", "NWE"],
    "kevin faulk": ["NWE"],
    "tedy bruschi": ["NWE"],
    "mike vrabel": ["PIT", "NWE", "KC"],
    "willie mcginest": ["NWE", "CLE"],
    "richard seymour": ["NWE", "LVR"],
    "ty law": ["NWE", "NYJ", "KC", "DEN"],
    "asante samuel": ["NWE", "PHI", "ATL"],
    "vince wilfork": ["NWE", "HOU"],
    "lawyer milloy": ["NWE", "BUF", "ATL", "SEA"],
    "ben watson": ["NWE", "CLE", "BAL", "NOR"],
    "bernie kosar": ["CLE", "DAL", "MIA"],  # not NWE
    "drew bledsoe": ["NWE", "BUF", "DAL"],
    "john hannah": ["NWE"],
    "stanley morgan": ["NWE"],
    "jim plunkett": ["NWE", "SFO", "LVR"],
    "mac jones": ["NWE", "JAX"],
    "ezekiel elliott": ["DAL", "NWE"],
    "jonnu smith": ["TEN", "NWE", "ATL", "MIA"],
    "hunter henry": ["LAC", "NWE"],

    # ===== Miami Dolphins (MIA) =====
    "tua tagovailoa": ["MIA"],
    "chop robinson": ["MIA"],
    "tyreek hill": ["KC", "MIA"],
    "jaylen waddle": ["MIA"],
    "jaelan phillips": ["MIA"],
    "dan marino": ["MIA"],
    "bob griese": ["MIA"],
    "larry csonka": ["MIA", "NYG"],
    "mercury morris": ["MIA"],
    "mark duper": ["MIA"],
    "mark clayton": ["MIA"],
    "jason taylor": ["MIA", "WAS", "NYJ"],
    "dwight stephenson": ["MIA"],
    "nick buoniconti": ["BOS", "MIA"],
    "larry little": ["MIA"],
    "jim langer": ["MIA"],
    "manny fernandez": ["MIA"],
    "jake scott": ["MIA"],
    "wes welker": ["MIA", "NWE", "DEN"],
    "ricky williams": ["NOR", "MIA"],
    "ronnie brown": ["MIA"],
    "reggie bush": ["NOR", "MIA", "DET"],
    "mike wallace": ["PIT", "MIA", "MIN", "BAL", "PHI"],
    "kenny stills": ["NOR", "MIA", "HOU"],
    "ryan fitzpatrick": ["LAR", "CIN", "BUF", "TEN", "HOU", "NYJ", "TAM", "MIA", "WAS"],
    "chad pennington": ["NYJ", "MIA"],
    "minkah fitzpatrick": ["MIA", "PIT"],
    "xavien howard": ["MIA"],
    "devante parker": ["MIA", "NWE"],
    "cris carter": ["PHI", "MIN", "MIA"],
    "greg jennings": ["GNB", "MIN", "MIA"],
    "zach thomas": ["MIA"],

    # ===== Buffalo Bills (BUF) =====
    "josh allen": ["BUF"],
    "stefon diggs": ["MIN", "BUF", "HOU"],
    "von miller": ["DEN", "LAR", "BUF"],
    "james lofton": ["GNB", "LVR", "BUF", "LAR", "PHI"],
    "jim kelly": ["BUF"],
    "thurman thomas": ["BUF"],
    "andre reed": ["BUF", "WAS"],
    "bruce smith": ["BUF", "WAS"],
    "cornelius bennett": ["BUF", "ATL", "IND"],
    "terrell owens": ["SFO", "PHI", "DAL", "BUF", "CIN"],
    "ryan fitzpatrick": ["LAR", "CIN", "BUF", "TEN", "HOU", "NYJ", "TAM", "MIA", "WAS"],
    "drew bledsoe": ["NWE", "BUF", "DAL"],
    "lesean mccoy": ["PHI", "BUF", "KC", "TAM"],
    "sam darnold": ["NYJ", "CAR", "SFO", "MIN"],
    "damar hamlin": ["BUF"],
    "tremaine edmunds": ["BUF", "CHI"],
    "tre'davious white": ["BUF"],
    "cole beasley": ["DAL", "BUF", "TAM"],
    "gabriel davis": ["BUF"],
    "dawson knox": ["BUF"],
    "jordan poyer": ["PHI", "BUF"],
    "micah hyde": ["GNB", "BUF"],
    "frank gore": ["SFO", "IND", "MIA", "BUF", "NYJ"],

    # ===== Baltimore Ravens (BAL) =====
    "lamar jackson": ["BAL"],
    "nate wiggins": ["BAL"],
    "justin tucker": ["BAL"],
    "mark andrews": ["BAL"],
    "roquan smith": ["CHI", "BAL"],
    "ed reed": ["BAL", "HOU", "NYJ"],
    "ray lewis": ["BAL"],
    "terrell suggs": ["BAL", "ARI", "KC"],
    "haloti ngata": ["BAL", "DET", "PHI"],
    "jonathan ogden": ["BAL"],
    "mike singletary": ["CHI"],  # not BAL
    "derrick mason": ["TEN", "BAL"],
    "anquan boldin": ["ARI", "BAL", "SFO", "DET", "BUF"],
    "torrey smith": ["BAL", "SFO", "PHI", "CAR"],
    "john harbaugh": [],  # coach
    "marshal yanda": ["BAL"],
    "matt birk": ["MIN", "BAL"],
    "michael oher": ["BAL", "TEN", "CAR"],
    "joe flacco": ["BAL", "DEN", "NYJ", "PHI", "CLE", "NYG"],
    "priest holmes": ["BAL", "KC"],
    "zadarius smith": ["BAL", "GNB", "MIN", "CLE", "DET"],
    "calais campbell": ["ARI", "JAX", "BAL", "ATL"],
    "odell beckham jr": ["NYG", "CLE", "LAR", "BAL"],
    "dalvin cook": ["MIN", "NYJ", "BAL", "DAL"],
    "marlon humphrey": ["BAL"],
    "tony jefferson": ["ARI", "BAL"],
    "c.j. mosley": ["BAL", "NYJ"],
    "chuck foreman": ["MIN"],  # not BAL
    "jimmy smith": ["JAX"],   # not BAL

    # ===== Los Angeles Rams (LAR) =====
    "jared verse": ["LAR"],
    "jared goff": ["LAR", "DET"],
    "matthew stafford": ["DET", "LAR"],
    "cooper kupp": ["LAR"],
    "puka nacua": ["LAR"],
    "davante adams": ["GNB", "LVR", "NYJ"],  # not LAR
    "joe noteboom": ["LAR"],
    "von miller": ["DEN", "LAR", "BUF"],
    "aaron donald": ["LAR"],
    "troy fautanu": ["PIT"],  # not LAR
    "james lofton": ["GNB", "LVR", "BUF", "LAR", "PHI"],
    "eric dickerson": ["LAR", "IND", "LAR", "ATL", "LVR"],
    "marshall faulk": ["IND", "LAR"],
    "isaac bruce": ["LAR"],
    "torry holt": ["LAR"],
    "orlando pace": ["LAR"],
    "kevin carter": ["LAR", "TEN", "TAM"],
    "leonard little": ["LAR"],
    "david baker": ["LAR"],
    "clay matthews": ["GNB", "LAR"],
    "terry baker": ["LAR"],
    "jack snow": ["LAR"],
    "roman gabriel": ["LAR", "PHI"],
    "merlin olsen": ["LAR"],
    "deacon jones": ["LAR", "WAS"],
    "elroy hirsch": ["CHI", "LAR"],
    "vince ferragamo": ["LAR"],
    "kurt warner": ["LAR", "NYG", "ARI"],
    "baker mayfield": ["CLE", "CAR", "LAR", "TAM"],
    "steven jackson": ["LAR"],
    "odell beckham jr": ["NYG", "CLE", "LAR", "BAL"],
    "brandin cooks": ["NOR", "NWE", "LAR", "HOU", "DAL"],
    "kenny easley": ["SEA"],  # not LAR
    "nick scott": ["LAR"],
    "robert woods": ["BUF", "LAR", "TEN"],
    "danny amendola": ["LAR", "NWE", "MIA", "PHI"],
    "tyler higbee": ["LAR"],
    "andrew whitworth": ["CIN", "LAR"],
    "jared allen": ["KC", "MIN", "CHI", "CAR"],  # not LAR
    "jamal adams": ["NYJ", "SEA", "LAR"],

    # ===== Las Vegas Raiders (LVR) =====
    "brock bowers": ["LVR"],
    "davante adams": ["GNB", "LVR", "NYJ"],
    "jerry rice": ["SFO", "LVR", "SEA"],
    "charles woodson": ["LVR", "GNB"],
    "james lofton": ["GNB", "LVR", "BUF", "LAR", "PHI"],
    "ronnie lott": ["SFO", "LVR", "NYJ"],
    "rod woodson": ["PIT", "SFO", "BAL", "LVR"],
    "ken stabler": ["LVR", "HOU", "NOR", "MIN"],
    "bo jackson": ["LVR"],
    "howie long": ["LVR"],
    "tim brown": ["LVR", "TAM"],
    "rich gannon": ["MIN", "WAS", "KC", "LVR"],
    "zach wilson": ["NYJ", "DEN"],  # not LVR
    "jordy nelson": ["GNB", "LVR"],
    "marshawn lynch": ["BUF", "SEA", "LVR"],
    "jason witten": ["DAL", "LVR", "LAR"],
    "khalil mack": ["LVR", "CHI", "LAC"],
    "richard seymour": ["NWE", "LVR"],
    "daunte culpepper": ["MIN", "MIA", "LVR", "DET"],
    "antonio brown": ["PIT", "LVR", "TAM"],
    "jamarcus russell": ["LVR"],
    "sebastian janikowski": ["LVR"],
    "marcus allen": ["LVR", "KC"],
    "jim plunkett": ["NWE", "SFO", "LVR"],
    "willie brown": ["DEN", "LVR"],
    "cornerback nnamdi asomugha": ["LVR"],
    "nnamdi asomugha": ["LVR", "PHI", "SFO"],
    "jon gruden": [],  # coach

    # ===== Seattle Seahawks (SEA) =====
    "jerry rice": ["SFO", "LVR", "SEA"],
    "warren moon": ["TEN", "MIN", "SEA", "KC"],
    "marshawn lynch": ["BUF", "SEA", "LVR"],
    "russell wilson": ["SEA", "DEN", "PIT"],
    "earl thomas": ["SEA", "BAL"],
    "richard sherman": ["SEA", "SFO"],
    "kam chancellor": ["SEA"],
    "bobby wagner": ["SEA", "LAR"],
    "k.j. wright": ["SEA"],
    "michael bennett": ["SEA", "PHI", "DAL"],
    "cliff avril": ["DET", "SEA"],
    "brandon mebane": ["SEA", "LAC"],
    "walter jones": ["SEA"],
    "steve hutchinson": ["SEA", "MIN"],
    "cortez kennedy": ["SEA"],
    "shaun alexander": ["SEA"],
    "steve largent": ["SEA"],
    "kenny easley": ["SEA"],
    "jim zorn": ["SEA"],
    "john carlson": ["SEA", "MIN"],
    "zach miller": ["LVR", "SEA"],
    "percy harvin": ["MIN", "SEA", "NYJ", "BUF"],
    "doug baldwin": ["SEA"],
    "tyler lockett": ["SEA"],
    "dk metcalf": ["SEA"],
    "ryan fitzpatrick": ["LAR", "CIN", "BUF", "TEN", "HOU", "NYJ", "TAM", "MIA", "WAS"],
    "geno smith": ["NYJ", "LAR", "LAC", "SEA"],
    "jake locker": ["TEN"],
    "mike williams": ["TEN"],  # different player
    "travis homer": ["SEA"],
    "devon witherspoon": ["SEA"],
    "jaxon smith-njigba": ["SEA"],
    "byron murphy ii": ["SEA"],
    "riq woolen": ["SEA"],

    # ===== Denver Broncos (DEN) =====
    "bo nix": ["DEN"],
    "peyton manning": ["IND", "DEN"],
    "john elway": ["DEN"],
    "terrell davis": ["DEN"],
    "rod smith": ["DEN"],
    "ed mccaffrey": ["NYG", "SFO", "DEN"],
    "shannon sharpe": ["DEN", "BAL"],
    "gary zimmerman": ["MIN", "DEN"],
    "von miller": ["DEN", "LAR", "BUF"],
    "demarcus ware": ["DAL", "DEN"],
    "champ bailey": ["WAS", "DEN"],
    "brian dawkins": ["PHI", "DEN"],
    "elvis dumervil": ["DEN", "BAL"],
    "nate jackson": ["SFO", "DEN"],
    "trevor siemian": ["DEN"],
    "zach wilson": ["NYJ", "DEN"],
    "patrick surtain ii": ["DEN"],
    "courtland sutton": ["DEN"],
    "javonte williams": ["DEN"],
    "jerry jeudy": ["DEN", "CLE"],
    "drew lock": ["DEN", "SEA", "NYG"],
    "will parks": ["DEN"],
    "kareem jackson": ["HOU", "DEN"],
    "randy gradishar": ["DEN"],
    "louis wright": ["DEN"],
    "tom jackson": ["DEN"],
    "rick upchurch": ["DEN"],
    "reilly odoms": ["DEN"],
    "gerald willhite": ["DEN"],
    "craig morton": ["DAL", "DEN"],
    "jason elam": ["DEN", "ATL"],
    "neil smith": ["KC", "DEN"],
    "bill romanowski": ["SFO", "PHI", "DEN", "LVR"],
    "lyle alzado": ["DEN", "CLE", "LVR"],
    "wes welker": ["MIA", "NWE", "DEN"],
    "kyle orton": ["CHI", "DEN", "KC", "BUF", "DAL"],
    "jake plummer": ["ARI", "DEN"],
    "brian griese": ["DEN", "MIA"],
    "jay cutler": ["DEN", "CHI"],
    "russell wilson": ["SEA", "DEN", "PIT"],
    "malik turner": ["SEA", "DEN"],

    # ===== Cincinnati Bengals (CIN) =====
    "joe burrow": ["CIN"],
    "ja'marr chase": ["CIN"],
    "jamarr chase": ["CIN"],
    "amarius mims": ["CIN"],
    "tee higgins": ["CIN"],
    "sam hubbard": ["CIN"],
    "paxton lynch": ["DEN", "SEA", "CIN"],
    "ryan fitzpatrick": ["LAR", "CIN", "BUF", "TEN", "HOU", "NYJ", "TAM", "MIA", "WAS"],
    "corey dillon": ["CIN", "NWE"],
    "terrell owens": ["SFO", "PHI", "DAL", "BUF", "CIN"],
    "tj houshmandzadeh": ["CIN", "SEA", "BAL"],
    "chad ochocinco": ["CIN", "NWE"],
    "chad johnson": ["CIN", "NWE"],
    "andrew whitworth": ["CIN", "LAR"],
    "willie anderson": ["CIN"],
    "ken riley": ["CIN"],
    "lemar parrish": ["CIN", "WAS"],
    "issac curtis": ["CIN"],
    "james brooks": ["LAC", "CIN", "CLE"],
    "james harrison": ["PIT", "CIN", "BAL"],
    "reggie nelson": ["JAX", "CIN", "LVR"],
    "ak green": ["CIN", "ARI"],
    "aj green": ["CIN", "ARI"],
    "a.j. green": ["CIN", "ARI"],
    "geno atkins": ["CIN"],
    "carl lawson": ["CIN", "NYJ"],
    "sam wyche": [],  # coach
    "boomer esiason": ["CIN", "NYJ", "ARI"],
    "andy dalton": ["CIN", "DAL", "CHI", "NYG", "NOR"],
    "hue jackson": [],  # coach

    # ===== Tampa Bay Buccaneers (TAM) =====
    "tom brady": ["NWE", "TAM"],
    "graham barton": ["TAM"],
    "rob gronkowski": ["NWE", "TAM"],
    "antonio brown": ["PIT", "LVR", "TAM"],
    "mike evans": ["TAM"],
    "chris godwin": ["TAM"],
    "lavonte david": ["TAM"],
    "devin white": ["TAM"],
    "shaquil barrett": ["DEN", "TAM"],
    "jason pierre-paul": ["NYG", "TAM", "BAL"],
    "ndamukong suh": ["DET", "MIA", "LAR", "TAM"],
    "darrelle revis": ["NYJ", "TAM", "NWE", "KC"],
    "simeon rice": ["ARI", "TAM", "DEN"],
    "warren sapp": ["TAM", "LVR"],
    "derrick brooks": ["TAM"],
    "ronde barber": ["TAM"],
    "brad johnson": ["MIN", "WAS", "TAM", "DAL"],
    "jameis winston": ["TAM", "NOR"],
    "ryan fitzpatrick": ["LAR", "CIN", "BUF", "TEN", "HOU", "NYJ", "TAM", "MIA", "WAS"],
    "lesean mccoy": ["PHI", "BUF", "KC", "TAM"],
    "leonard fournette": ["JAX", "TAM"],
    "keyshawn johnson": ["NYJ", "TAM", "DAL", "CAR"],
    "steve young": ["TAM", "SFO"],
    "mike alstott": ["TAM"],
    "john lynch": ["TAM", "DEN"],
    "karl williams": ["TAM"],
    "sam wyche": [],  # coach
    "baker mayfield": ["CLE", "CAR", "LAR", "TAM"],

    # ===== Tennessee Titans / Houston Oilers (TEN) =====
    "jc latham": ["TEN"],
    "derrick henry": ["TEN", "BAL"],
    "aq brown": ["TEN", "PHI"],
    "aj brown": ["TEN", "PHI"],
    "corey davis": ["TEN", "NYJ"],
    "kevin byard": ["TEN", "PHI"],
    "ben jones": ["HOU", "TEN"],
    "ryan tannehill": ["MIA", "TEN"],
    "warren moon": ["TEN", "MIN", "SEA", "KC"],
    "kenny britt": ["TEN"],
    "nikola jones": ["TEN"],
    "dan marino": ["MIA"],  # not TEN
    "steve mcnair": ["TEN", "BAL"],
    "eddie george": ["TEN", "DAL"],
    "frank wycheck": ["TEN"],
    "blaine bishop": ["TEN", "ATL", "PHI"],
    "die hard fan": [],
    "mike keith": [],
    "earl campbell": ["TEN"],
    "randy moss": ["MIN", "LVR", "NWE", "TEN", "SFO"],
    "vince young": ["TEN"],
    "chris johnson": ["TEN", "NYJ", "ARI"],
    "jacob ford": ["TEN"],
    "jared allen": ["KC", "MIN", "CHI", "CAR"],
    "robert mathis": ["IND"],
    "derrick mason": ["TEN", "BAL"],
    "gary anderson": ["PIT", "MIN", "PHI", "SFO"],
    "hakim": ["TEN"],
    "jon bell": ["TEN"],

    # ===== Indianapolis Colts (IND) =====
    "laiatu latu": ["IND"],
    "peyton manning": ["IND", "DEN"],
    "marvin harrison": ["IND"],
    "reggie wayne": ["IND"],
    "edgerrin james": ["IND", "ARI", "SEA", "PIT"],
    "dallas clark": ["IND"],
    "dwight freeney": ["IND", "ARI", "ATL", "LAC"],
    "robert mathis": ["IND"],
    "tarik glenn": ["IND"],
    "jeff saturday": ["IND", "GNB"],
    "bob sanders": ["IND"],
    "adam vinatieri": ["NWE", "IND"],
    "austin collie": ["IND", "NWE"],
    "marshall faulk": ["IND", "LAR"],
    "eric dickerson": ["LAR", "IND", "LAR", "ATL", "LVR"],
    "tony dungy": [],  # coach
    "sam ehlinger": ["IND"],
    "jonathan taylor": ["IND"],
    "michael pittman jr": ["IND"],
    "zack moss": ["BUF", "IND", "CIN"],
    "xavier rhodes": ["MIN", "IND", "ATL"],
    "frank gore": ["SFO", "IND", "MIA", "BUF", "NYJ"],
    "andrew luck": ["IND"],
    "ryan tannehill": ["MIA", "TEN"],
    "adam vinatieri": ["NWE", "IND"],
    "ted hendricks": ["BAL", "GNB", "LVR"],
    "cornelius bennett": ["BUF", "ATL", "IND"],
    "will levis": ["TEN"],
    "kwity paye": ["IND"],
    "grover stewart": ["IND"],
    "darius leonard": ["IND"],
    "shaquille leonard": ["IND"],
    "quenton nelson": ["IND"],
    "braden smith": ["IND"],
    "ryan kelly": ["IND"],

    # ===== Jacksonville Jaguars (JAX) =====
    "trevor lawrence": ["JAX"],
    "brian thomas jr": ["JAX"],
    "travis etienne": ["JAX"],
    "devin lloyd": ["JAX"],
    "josh allen jax": ["JAX"],
    "mac jones": ["NWE", "JAX"],
    "fred taylor": ["JAX"],
    "jimmy smith": ["JAX"],
    "tony brackens": ["JAX"],
    "john henderson": ["JAX"],
    "marcus stroud": ["JAX", "BUF"],
    "rashean mathis": ["JAX", "DET"],
    "reggie nelson": ["JAX", "CIN", "LVR"],
    "mark brunell": ["GNB", "JAX", "WAS", "NYJ", "NOR"],
    "blake bortles": ["JAX", "LAR", "GNB", "NOR"],
    "nick foles": ["PHI", "LAR", "JAX", "CHI", "IND"],
    "leonard fournette": ["JAX", "TAM"],
    "calais campbell": ["ARI", "JAX", "BAL", "ATL"],
    "yannick ngakoue": ["JAX", "MIN", "BAL", "LVR", "CHI"],
    "myles jack": ["JAX", "PIT"],

    # ===== Houston Texans (HOU) =====
    "cj stroud": ["HOU"],
    "c.j. stroud": ["HOU"],
    "stefon diggs": ["MIN", "BUF", "HOU"],
    "danielle hunter": ["MIN", "HOU"],
    "will anderson jr": ["HOU"],
    "nico collins": ["HOU"],
    "ed reed": ["BAL", "HOU", "NYJ"],
    "vince wilfork": ["NWE", "HOU"],
    "j.j. watt": ["HOU", "ARI"],
    "jj watt": ["HOU", "ARI"],
    "andre johnson": ["HOU"],
    "arian foster": ["HOU"],
    "deandre hopkins": ["HOU", "ARI", "TEN", "LAR"],
    "kareem jackson": ["HOU", "DEN"],
    "duane brown": ["HOU", "SEA", "NYJ"],
    "ryan fitzpatrick": ["LAR", "CIN", "BUF", "TEN", "HOU", "NYJ", "TAM", "MIA", "WAS"],
    "marcus colston": ["NOR"],
    "owen daniels": ["HOU", "BAL", "DEN"],
    "randall cobb": ["GNB", "DAL", "HOU", "NYG"],
    "deshaun watson": ["HOU", "CLE"],
    "brandin cooks": ["NOR", "NWE", "LAR", "HOU", "DAL"],
    "ken burrough": ["HOU"],
    "billy johnson": ["HOU", "ATL"],
    "bob young": ["HOU"],
    "elbert shelley": ["ATL"],
    "kevin walter": ["CIN", "HOU"],

    # ===== Carolina Panthers (CAR) =====
    "xavier legette": ["CAR"],
    "bryce young": ["CAR"],
    "miles sanders": ["PHI", "CAR"],
    "diontae johnson": ["PIT", "CAR", "BAL"],
    "christian mccaffrey": ["CAR", "SFO"],
    "cam newton": ["CAR", "NWE"],
    "steve smith sr": ["CAR", "BAL"],
    "jonathan stewart": ["CAR"],
    "deangelo williams": ["CAR", "PIT"],
    "julius peppers": ["CAR", "CHI", "GNB"],
    "reggie white": ["PHI", "GNB", "CAR"],
    "jared allen": ["KC", "MIN", "CHI", "CAR"],
    "baker mayfield": ["CLE", "CAR", "LAR", "TAM"],
    "sam darnold": ["NYJ", "CAR", "SFO", "MIN"],
    "chris weinke": ["CAR"],
    "keyshawn johnson": ["NYJ", "TAM", "DAL", "CAR"],
    "mike rucker": ["CAR"],
    "captain munnerlyn": ["CAR", "MIN", "CHI"],
    "richard marshall": ["CAR"],
    "jake delhomme": ["NOR", "CAR", "CLE"],

    # ===== Atlanta Falcons (ATL) =====
    "michael penix jr": ["ATL"],
    "kirk cousins": ["WAS", "MIN", "ATL"],
    "bijan robinson": ["ATL"],
    "kyle pitts": ["ATL"],
    "drake london": ["ATL"],
    "grady jarrett": ["ATL"],
    "matt ryan": ["ATL", "IND"],
    "julio jones": ["ATL", "TEN", "TAM"],
    "roddy white": ["ATL"],
    "tony gonzalez": ["KC", "ATL"],
    "deion sanders": ["ATL", "SFO", "DAL", "WAS", "BAL"],
    "brett favre": ["ATL", "GNB", "NYJ", "MIN"],
    "mike vick": ["ATL", "PHI", "NYJ", "PIT"],
    "michael vick": ["ATL", "PHI", "NYJ", "PIT"],
    "chris chandler": ["IND", "PHO", "LAR", "TAM", "HOU", "ATL"],
    "warrick dunn": ["TAM", "ATL"],
    "aj terrell": ["ATL"],
    "rashaan evans": ["TEN", "ATL"],
    "keanu neal": ["ATL", "DAL", "TEN"],
    "desmond trufant": ["ATL", "DET"],
    "vic beasley": ["ATL", "TEN"],
    "chris olave": ["NOR"],  # not ATL
    "todd mcclure": ["ATL"],
    "mack ryan": ["ATL"],
    "claude humphrey": ["ATL", "PHI"],
    "tommy nobis": ["ATL"],
    "eric metcalf": ["CLE", "ATL"],
    "jamal anderson": ["ATL"],
    "alfred jenkins": ["ATL"],
    "steve bartkowski": ["ATL"],
    "cornell green": ["DAL"],

    # ===== New Orleans Saints (NOR) =====
    "taliese fuaga": ["NOR"],
    "chris olave": ["NOR"],
    "alvin kamara": ["NOR"],
    "derek carr": ["LVR", "NOR"],
    "drew brees": ["LAC", "NOR"],
    "marques colston": ["NOR"],
    "devery henderson": ["NOR"],
    "reggie bush": ["NOR", "MIA", "DET"],
    "pierre thomas": ["NOR"],
    "darren sproles": ["LAC", "NOR", "PHI"],
    "jimmy graham": ["NOR", "SEA", "GNB", "CHI"],
    "will smith": ["NOR"],
    "roman harper": ["NOR"],
    "malcolm jenkins": ["NOR", "PHI"],
    "jameis winston": ["TAM", "NOR"],
    "ricky williams": ["NOR", "MIA"],
    "joe horn": ["NOR"],
    "archie manning": ["NOR", "HOU", "MIN"],
    "morten andersen": ["NOR", "ATL"],
    "darren sharper": ["GNB", "MIN", "NOR"],

    # ===== New York Giants (NYG) =====
    "malik nabers": ["NYG"],
    "daniel jones": ["NYG"],
    "dexter lawrence": ["NYG"],
    "saquon barkley": ["NYG", "PHI"],
    "eli manning": ["NYG"],
    "odell beckham jr": ["NYG", "CLE", "LAR", "BAL"],
    "victor cruz": ["NYG"],
    "randall cobb": ["GNB", "DAL", "HOU", "NYG"],
    "sterling shepard": ["NYG"],
    "leonard williams": ["NYJ", "NYG"],
    "jason pierre-paul": ["NYG", "TAM", "BAL"],
    "brad van pelt": ["NYG"],
    "harry carson": ["NYG"],
    "lawrence taylor": ["NYG"],
    "michael strahan": ["NYG"],
    "tiki barber": ["NYG"],
    "amani toomer": ["NYG"],
    "plaxico burress": ["PIT", "NYG", "NYJ"],
    "jeremy shockey": ["NYG", "NOR"],
    "osi umenyiora": ["NYG", "ATL"],
    "justin tuck": ["NYG", "LVR"],
    "fran tarkenton": ["MIN", "NYG"],
    "y.a. tittle": ["SFO", "NYG"],
    "frank gifford": ["NYG"],
    "roosevelt brown": ["NYG"],
    "dave meggett": ["NYG", "NWE", "NYJ"],
    "ottis anderson": ["STL", "NYG"],
    "mark bavaro": ["NYG", "CLE"],
    "kurt warner": ["LAR", "NYG", "ARI"],
    "david tyree": ["NYG"],
    "hakeem nicks": ["NYG"],
    "kenny golladay": ["DET", "NYG"],
    "kyle rudolph": ["MIN", "NYG"],

    # ===== Washington Commanders (WAS) =====
    "jayden daniels": ["WAS"],
    "devin butler": ["WAS"],
    "montez sweat": ["WAS", "CHI"],
    "terry mclaurin": ["WAS"],
    "jonathan allen": ["WAS"],
    "daron payne": ["WAS"],
    "christian darrisaw": ["MIN"],
    "joe theismann": ["WAS"],
    "john riggins": ["NYJ", "WAS"],
    "sonny jurgensen": ["PHI", "WAS"],
    "charley taylor": ["WAS"],
    "art monk": ["WAS"],
    "gary clark": ["WAS"],
    "ricky sanders": ["WAS"],
    "mark rypen": ["WAS"],
    "darrell green": ["WAS"],
    "mark moseley": ["WAS"],
    "len hauss": ["WAS"],
    "chris cooley": ["WAS"],
    "patrick ramsey": ["WAS"],
    "donovan mcnabb": ["PHI", "WAS"],
    "rex grossman": ["CHI", "WAS", "HOU"],
    "mark sanchez": ["NYJ", "PHI", "DAL", "WAS"],
    "ryan fitzpatrick": ["LAR", "CIN", "BUF", "TEN", "HOU", "NYJ", "TAM", "MIA", "WAS"],
    "champ bailey": ["WAS", "DEN"],
    "paul krause": ["WAS", "MIN"],
    "sam huff": ["NYG", "WAS"],
    "deron cherry": ["KC"],
    "clinton portis": ["DEN", "WAS"],
    "ladainian tomlinson": ["LAC", "NYJ"],
    "desean jackson": ["PHI", "WAS", "TAM", "LAR"],
    "pierre garcon": ["IND", "WAS", "SFO"],
    "chase young": ["WAS", "SFO"],
    "trent williams": ["WAS", "SFO"],

    # ===== Arizona Cardinals (ARI) =====
    "marvin harrison jr": ["ARI"],
    "kyler murray": ["ARI"],
    "james conner": ["PIT", "ARI"],
    "deandre hopkins": ["HOU", "ARI", "TEN", "LAR"],
    "davida johnson": ["ARI"],
    "jj watt": ["HOU", "ARI"],
    "j.j. watt": ["HOU", "ARI"],
    "chandler jones": ["NWE", "ARI"],
    "patrick peterson": ["ARI", "MIN", "PIT"],
    "duane tillman": ["ARI"],
    "david johnson": ["ARI"],
    "larry fitzgerald": ["ARI"],
    "anquan boldin": ["ARI", "BAL", "SFO", "DET", "BUF"],
    "calais campbell": ["ARI", "JAX", "BAL", "ATL"],
    "kurt warner": ["LAR", "NYG", "ARI"],
    "jake plummer": ["ARI", "DEN"],
    "neil lomax": ["ARI"],
    "dan majerle": [],
    "emmitt smith": ["DAL", "ARI"],
    "eye frank sanders": ["ARI"],
    "bob paluck": ["WAS", "HOU"],
    "duane walker": [],
    "aeneas williams": ["ARI", "LAR"],
    "eric swann": ["ARI"],
    "eric metcalf": ["CLE", "ATL"],
    "simeon rice": ["ARI", "TAM", "DEN"],
    "hasson reddick": ["ARI", "CAR", "PHI", "NYJ"],
    "haason reddick": ["ARI", "CAR", "PHI", "NYJ"],
    "darius robinson": ["ARI"],

    # ===== Cleveland Browns (CLE) =====
    "nick chubb": ["CLE"],
    "amari cooper": ["LVR", "DAL", "CLE", "BUF"],
    "jim brown": ["CLE"],
    "ozzie newsome": ["CLE"],
    "bernie kosar": ["CLE", "DAL", "MIA"],
    "leroy kelly": ["CLE"],
    "lou groza": ["CLE"],
    "frank minnifield": ["CLE"],
    "hanford dixon": ["CLE"],
    "clay matthews sr": ["CLE"],
    "clay matthews": ["GNB", "LAR"],  # jr - green bay
    "myles garrett": ["CLE"],
    "dawand jones": ["CLE"],
    "deshaun watson": ["HOU", "CLE"],
    "baker mayfield": ["CLE", "CAR", "LAR", "TAM"],
    "odell beckham jr": ["NYG", "CLE", "LAR", "BAL"],
    "zadarius smith": ["BAL", "GNB", "MIN", "CLE", "DET"],
    "greg pruitt": ["CLE"],
    "paul warfield": ["CLE", "MIA"],

    # ===== Chicago Bears (CHI) =====
    "caleb williams": ["CHI"],
    "rome odunze": ["CHI"],
    "khalil mack": ["LVR", "CHI", "LAC"],
    "roquan smith": ["CHI", "BAL"],
    "mike ditka": ["CHI", "PHI", "DAL"],  # TE not coach
    "dick butkus": ["CHI"],
    "mike singletary": ["CHI"],
    "walter payton": ["CHI"],
    "gale sayers": ["CHI"],
    "devin hester": ["CHI", "ATL", "SFO", "SEA"],
    "lovie smith": [],  # coach
    "brian urlacher": ["CHI"],
    "lance briggs": ["CHI"],
    "julius peppers": ["CAR", "CHI", "GNB"],
    "allen robinson": ["JAX", "CHI", "LAR"],
    "alshon jeffery": ["CHI", "PHI"],
    "mike evans": ["TAM"],
    "alan page": ["MIN", "CHI"],
    "jim mcmahon": ["CHI", "GNB", "MIN"],
    "jay cutler": ["DEN", "CHI"],
    "rex grossman": ["CHI", "WAS", "HOU"],
    "kyle orton": ["CHI", "DEN", "KC", "BUF", "DAL"],
    "trubisky": ["CHI", "BUF", "PIT"],
    "mitchell trubisky": ["CHI", "BUF", "PIT"],
    "justin fields": ["CHI", "PIT"],
    "david montgomery": ["CHI", "DET"],
    "michael thomas": ["NOR"],  # not CHI

    # ===== Detroit Lions (DET) =====
    "terrion arnold": ["DET"],
    "jared goff": ["LAR", "DET"],
    "matthew stafford": ["DET", "LAR"],
    "amon-ra st. brown": ["DET"],
    "jameson williams": ["DET"],
    "tj hockenson": ["DET", "MIN"],
    "t.j. hockenson": ["DET", "MIN"],
    "penei sewell": ["DET"],
    "barry sanders": ["DET"],
    "calvin johnson": ["DET"],
    "herman moore": ["DET"],
    "brett perriman": ["DET", "MIA"],
    "darius slay": ["DET", "PHI"],
    "jeff okudah": ["DET"],
    "david montgomery": ["CHI", "DET"],
    "jahmyr gibbs": ["DET"],
    "sam la porta": ["DET"],
    "ndamukong suh": ["DET", "MIA", "LAR", "TAM"],
    "haloti ngata": ["BAL", "DET", "PHI"],
    "eric ebron": ["DET", "IND", "PIT"],
    "matthew stafford": ["DET", "LAR"],
    "mike furrey": ["LAR", "DET", "CLE"],
    "ron rice": ["DET"],
    "glover quin": ["HOU", "DET"],
    "danny amendola": ["LAR", "NWE", "MIA", "PHI"],

    # ===== Los Angeles Chargers (LAC) =====
    "justin herbert": ["LAC"],
    "joe alt": ["LAC"],
    "khalil mack": ["LVR", "CHI", "LAC"],
    "keenan allen": ["LAC", "CHI"],
    "joey bosa": ["LAC"],
    "austin ekeler": ["LAC"],
    "mike williams lac": ["LAC"],
    "jason verrett": ["LAC"],
    "melvin gordon": ["LAC", "DEN", "HOU"],
    "antonio gates": ["LAC"],
    "philip rivers": ["LAC"],
    "dan fouts": ["LAC"],
    "charlie joiner": ["HOU", "CIN", "LAC"],
    "lance alworth": ["LAC", "DAL"],
    "drew brees": ["LAC", "NOR"],
    "darren sproles": ["LAC", "NOR", "PHI"],
    "ladainian tomlinson": ["LAC", "NYJ"],
    "lt": ["LAC", "NYJ"],  # LaDainian Tomlinson alias
    "donnie edwards": ["KC", "LAC"],
    "ig junior seau": ["LAC", "MIA", "NWE"],
    "junior seau": ["LAC", "MIA", "NWE"],
    "ryan leaf": ["LAC"],
    "stan humphries": ["WAS", "LAC"],
    "billy volek": ["TEN", "LAC"],
    "miles davis": [],
    "quentin jammer": ["LAC"],
    "eric weddle": ["LAC", "BAL", "LAR"],
    "jahleel addae": ["LAC"],
    "trey lance": ["SFO", "DAL"],

    # ===== Other Modern Stars (multi-franchise) =====
    "deandre hopkins": ["HOU", "ARI", "TEN", "LAR"],
    "julio jones": ["ATL", "TEN", "TAM"],
    "odell beckham jr": ["NYG", "CLE", "LAR", "BAL"],
    "stefon diggs": ["MIN", "BUF", "HOU"],
    "tyreek hill": ["KC", "MIA"],
    "davante adams": ["GNB", "LVR", "NYJ"],
    "amari cooper": ["LVR", "DAL", "CLE", "BUF"],
    "cooper kupp": ["LAR"],
    "christian mccaffrey": ["CAR", "SFO"],
    "saquon barkley": ["NYG", "PHI"],
    "nick chubb": ["CLE"],
    "derrick henry": ["TEN", "BAL"],
    "josh jacobs": ["LVR", "GNB"],
    "ezekiel elliott": ["DAL", "NWE"],
    "leonard fournette": ["JAX", "TAM"],
    "dalvin cook": ["MIN", "NYJ", "BAL", "DAL"],
    "travis etienne": ["JAX"],
    "clyde edwards-helaire": ["KC"],
    "james conner": ["PIT", "ARI"],
    "alvin kamara": ["NOR"],
    "joe mixon": ["CIN", "HOU"],
    "jonathan taylor": ["IND"],
    "najee harris": ["PIT"],
    "bijan robinson": ["ATL"],
    "jahmyr gibbs": ["DET"],
    "breece hall": ["NYJ"],
    "dj moore": ["CAR", "CHI"],
    "d.j. moore": ["CAR", "CHI"],
    "aj brown": ["TEN", "PHI"],
    "devonta smith": ["PHI"],
    "jaylen waddle": ["MIA"],
    "chris olave": ["NOR"],
    "drake london": ["ATL"],
    "garrett wilson": ["NYJ"],
    "jaxon smith-njigba": ["SEA"],
    "puka nacua": ["LAR"],
    "nico collins": ["HOU"],
    "malik nabers": ["NYG"],
    "rome odunze": ["CHI"],
    "marvin harrison jr": ["ARI"],
    "ladd mcconkey": ["LAC"],
    "xavier worthy": ["KC"],
    "malik washington": ["DEN"],
    "caleb williams": ["CHI"],
    "jayden daniels": ["WAS"],
    "drake maye": ["NWE"],
    "bo nix": ["DEN"],
    "cj stroud": ["HOU"],
    "c.j. stroud": ["HOU"],
    "trevor lawrence": ["JAX"],
    "bryce young": ["CAR"],
    "anthony richardson": ["IND"],
    "will levis": ["TEN"],
    "sam howell": ["WAS"],
    "aidan o'connell": ["LVR"],
    "jj mccarthy": ["MIN"],
    "j.j. mccarthy": ["MIN"],
    "jordan love": ["GNB"],
    "brock purdy": ["SFO"],
    "dak prescott": ["DAL"],
    "jalen hurts": ["PHI"],
    "lamar jackson": ["BAL"],
    "joe burrow": ["CIN"],
    "josh allen": ["BUF"],
    "patrick mahomes": ["KC"],
    "justin herbert": ["LAC"],
    "tua tagovailoa": ["MIA"],
    "kyler murray": ["ARI"],
    "baker mayfield": ["CLE", "CAR", "LAR", "TAM"],
    "geno smith": ["NYJ", "LAR", "LAC", "SEA"],
    "russell wilson": ["SEA", "DEN", "PIT"],
    "sam darnold": ["NYJ", "CAR", "SFO", "MIN"],
    "mac jones": ["NWE", "JAX"],
    "trey lance": ["SFO", "DAL"],
    "justin fields": ["CHI", "PIT"],
}

# ---------------------------------------------------------------------------
# 4,000+ Passing Yards in a Single Season
# ---------------------------------------------------------------------------
CANONICAL_PASSING_4000_YARD_PLAYERS: Set[str] = {
    "patrick mahomes", "peyton manning", "eli manning", "aaron rodgers", "matthew stafford",
    "josh allen", "philip rivers", "carson palmer", "jared goff", "baker mayfield",
    "joe burrow", "trevor lawrence", "cj stroud", "c.j. stroud", "jordan love",
    "cam newton", "daunte culpepper", "carson wentz", "alex smith", "vinny testaverde",
    "drew bledsoe", "michael vick", "jay cutler", "sam darnold", "kirk cousins",
    "tom brady", "drew brees", "dan marino", "kurt warner", "warren moon",
    "dan fouts", "matt ryan", "ben roethlisberger", "justin herbert", "dak prescott",
    "brock purdy", "caleb williams", "jayden daniels", "drake maye", "cam ward",
    "shedeur sanders", "arch manning", "tua tagovailoa", "deshaun watson", "ryan tannehill",
    "jameis winston", "andrew luck", "tony romo", "matt schaub", "marc bulger",
    "trent green", "jeff garcia", "rich gannon", "steve beuerlein", "brad johnson",
    "neil lomax", "bill kenney", "lynn dickey", "brian sipe", "joe namath",
    "lamar jackson", "jalen hurts", "kyler murray",
}

# ---------------------------------------------------------------------------
# 1,000+ Rushing Yards in a Single Season
# ---------------------------------------------------------------------------
CANONICAL_RUSH_1000_PLAYERS: Set[str] = {
    "emmitt smith", "barry sanders", "walter payton", "eric dickerson", "jim brown",
    "ladainian tomlinson", "lt", "christian mccaffrey", "derrick henry", "adrian peterson",
    "marshall faulk", "earl campbell", "franco harris", "tony dorsett", "gale sayers",
    "marcus allen", "jerome bettis", "john riggins", "thurman thomas", "barry word",
    "jamal lewis", "tiki barber", "clinton portis", "edgerrin james", "shaun alexander",
    "ricky williams", "fred taylor", "stephen davis", "corey dillon", "warrick dunn",
    "duce staley", "deuce mcallister", "lamar smith", "tatum bell", "dominic rhodes",
    "thomas jones", "kevin jones", "cedric benson", "joseph addai", "larry johnson",
    "brian westbrook", "michael turner", "ray rice", "arian foster", "frank gore",
    "lesean mccoy", "shady mccoy", "jamaal charles", "steven jackson", "deangelo williams",
    "jonathan stewart", "rashad jennings", "reggie bush", "marshawn lynch", "beast mode",
    "matt forte", "arian foster", "ryan mathews", "c.j. spiller", "c j spiller",
    "alfred morris", "demarco murray", "eddie lacy", "le'veon bell", "leveon bell",
    "todd gurley", "ezekiel elliott", "kareem hunt", "alvin kamara", "james conner",
    "joe mixon", "dalvin cook", "saquon barkley", "nick chubb", "josh jacobs",
    "devonta freeman", "mark ingram", "ty montgomery", "tevin coleman", "damien williams",
    "phillip lindsay", "sony michel", "damien harris", "najee harris", "jonathan taylor",
    "austin ekeler", "david montgomery", "dontrell hilliard", "d'andre swift", "miles sanders",
    "elijah mitchell", "leonard fournette", "travis etienne", "tony pollard", "rhamondre stevenson",
    "isaiah pacheco", "bijan robinson", "jahmyr gibbs", "breece hall", "derrick henry",
    "dalvin cook", "d'onta foreman", "chuba hubbard", "ty johnson",
    "eric dickerson", "chuck foreman", "samkon gado", "priest holmes", "jamal anderson",
    "larry csonka", "ottis anderson", "george rogers", "herschel walker", "alonzo highsmith",
    "roger craig", "wendell tyler", "joe washington", "freeman mcneil", "joe cribbs",
    "mark van eeghen", "clarence davis", "john fuqua", "rocky bleier",
    # 2024+ recent 1000-yard rushers
    "ashton jeanty", "quinshon judkins", "kaleb johnson", "omarion hampton",
}

# ---------------------------------------------------------------------------
# 1,000+ Receiving Yards in a Single Season
# ---------------------------------------------------------------------------
CANONICAL_REC_1000_PLAYERS: Set[str] = {
    "jerry rice", "randy moss", "terrell owens", "cris carter", "tim brown",
    "michael irvin", "james lofton", "calvin johnson", "larry fitzgerald", "anquan boldin",
    "marvin harrison", "reggie wayne", "torry holt", "isaac bruce", "sterling sharpe",
    "antonio brown", "dez bryant", "julio jones", "aj green", "a.j. green",
    "odell beckham jr", "davante adams", "tyreek hill", "deandre hopkins", "stefon diggs",
    "allen robinson", "mike evans", "adam thielen", "amari cooper", "sammy watkins",
    "brandin cooks", "demaryius thomas", "eric decker", "eric deckerr", "vincent jackson",
    "alshon jeffery", "kendall wright", "victor cruz", "wes welker", "reggie wayne",
    "donald driver", "greg jennings", "andre johnson", "kevin walter", "rod smith",
    "peerless price", "jimmy smith", "keenan mccardell", "joey galloway", "keyshawn johnson",
    "albert connell", "rod gardner", "laveranues coles", "jerricho cotchery", "plaxico burress",
    "mark duper", "mark clayton", "john taylor", "gary clark", "art monk",
    "ricky sanders", "henry ellard", "flipper anderson", "ron brown", "ron clark",
    "sean dawkins", "nate burleson", "kevin johnson", "oronde gadsden",
    "charlie joiner", "chuck foreman", "harold jackson", "harold carmichael",
    "russ francis", "john stallworth", "lynn swann", "don maynard", "lance alworth",
    "bob hayes", "cris collinsworth", "steve watson", "drew hill",
    "dee ford", "chad ochocinco", "chad johnson", "tj houshmandzadeh",
    "travis kelce", "rob gronkowski", "tony gonzalez", "jimmy graham", "jason witten",
    "mike ditka", "ozzie newsome", "kellen winslow",
    "justin jefferson", "jamarr chase", "ja'marr chase", "ceedee lamb", "garrett wilson",
    "aj brown", "devonta smith", "deebo samuel", "jaylen waddle", "cooper kupp",
    "diontae johnson", "tyler lockett", "dk metcalf", "brandon aiyuk", "chris olave",
    "tee higgins", "stefon diggs", "puka nacua", "nico collins", "malik nabers",
    "marvin harrison jr", "rome odunze", "drake london", "adam thielen",
    "michael pittman jr", "dk metcalf", "tyler lockett", "josh reynolds",
    "christian mccaffrey", "alvin kamara", "travis kelce",  # pass-catching flex
    "kyle pitts", "mark andrews", "george kittle", "darren waller",
    "tj hockenson", "t.j. hockenson", "dallas goedert", "pat freiermuth",
}

# ---------------------------------------------------------------------------
# 10.0+ Sacks in a Single Season
# ---------------------------------------------------------------------------
CANONICAL_SACK_10_PLAYERS: Set[str] = {
    "michael strahan", "jj watt", "j.j. watt", "reggie white", "bruce smith",
    "lawrence taylor", "derrick thomas", "demarcus ware", "von miller", "julius peppers",
    "dwight freeney", "jared allen", "robert mathis", "cliff avril", "clay matthews",
    "khalil mack", "t.j. watt", "tj watt", "myles garrett", "nick bosa",
    "maxx crosby", "micah parsons", "haason reddick", "hasson reddick", "chandler jones",
    "carlos dunlap", "joey bosa", "fletcher cox", "alan branch", "dante fowler",
    "harold landry", "leonard floyd", "za'darius smith", "zadarius smith",
    "rashan gary", "danielle hunter", "devin white", "kayvon thibodeaux",
    "will anderson jr", "edge nolan smith", "brian burns", "yannick ngakoue",
    "chris jones", "frank clark", "dee ford", "everson griffen",
    "cam jordan", "charles haley", "chris doleman", "neil smith",
    "harvey armstrong", "marc gastineau", "mark gastineau", "lyle alzado",
    "kevin greene", "rickey jackson", "fred dean", "deacon jones",
    "jack youngblood", "andy robustelli",
    "michael bennett", "greg hardy", "mario williams", "terrell suggs",
    "elvis dumervil", "lamarr woodley", "james harrison", "dwight smith",
    "ray lewis", "derrick brooks",  # occasional sack leaders
    "patrick kerney", "aaron kampman", "ryan kerrigan", "tamba hali",
    "glen dorsey", "dwan edwards", "andre carter",
    "frank clark", "dee ford", "calais campbell", "bennie logan",
    "linval joseph", "derek wolfe",
}

# ---------------------------------------------------------------------------
# Hall of Fame inductees (as players)
# ---------------------------------------------------------------------------
CANONICAL_HALL_OF_FAME_PLAYERS: Set[str] = {
    "brett favre", "bart starr", "reggie white", "james lofton", "charles woodson",
    "leroy butler", "joe namath", "curtis martin", "darrelle revis", "ronnie lott",
    "ed reed", "peyton manning", "tom brady", "drew brees", "dan marino",
    "kurt warner", "warren moon", "dan fouts", "steve young", "joe montana",
    "john elway", "troy aikman", "roger staubach", "terry bradshaw", "fran tarkenton",
    "emmitt smith", "barry sanders", "walter payton", "eric dickerson", "jim brown",
    "oj simpson", "o.j. simpson", "earl campbell", "marshall faulk", "jerome bettis",
    "tony dorsett", "marcus allen", "john riggins", "franco harris", "gale sayers",
    "jerry rice", "randy moss", "terrell owens", "cris carter", "calvin johnson",
    "tim brown", "michael irvin", "steve largent", "andre reed", "tony gonzalez",
    "shannon sharpe", "ozzie newsome", "mike ditka", "bruce smith", "michael strahan",
    "lawrence taylor", "derrick thomas", "dwight freeney", "julius peppers", "demarcus ware",
    "ray lewis", "brian urlacher", "mike singletary", "dick butkus", "jack lambert",
    "junior seau", "derrick brooks", "patrick willis", "deion sanders", "rod woodson",
    "troy polamalu", "champ bailey", "brian dawkins", "steve atwater", "john lynch",
    # Additional HOF inductees
    "ladainian tomlinson", "lt", "marvin harrison", "edgerrin james", "alan faneca",
    "willie roaf", "cortez kennedy", "john randle", "richard dent", "kevin mawae",
    "isaac bruce", "torry holt", "anquan boldin", "cliff avril", "don coryell",
    "jimmie johnson", "harold carmichael", "ken houston", "mel blount", "jack ham",
    "franco harris", "lynn swann", "john stallworth", "mike webster", "chuck noll",
    "eric dickerson", "jim kelly", "thurman thomas", "andre reed", "bruce smith",
    "bill polian", "don shula", "tom flores",
    # Greats who will likely be inducted
    "tony gonzalez", "darrell green", "joe delamielleure", "russ grimm",
}

# Dynamically load all 480+ Pro Football Hall of Fame inductees and their franchises
_hof_file = os.path.join(os.path.dirname(__file__), "all_hof_inductees.json")
if os.path.exists(_hof_file):
    try:
        with open(_hof_file, "r", encoding="utf-8") as _f:
            _hof_data = json.load(_f)
            for _ind in _hof_data:
                _raw_name = _ind.get("name", "").strip().lower()
                if _raw_name:
                    CANONICAL_HALL_OF_FAME_PLAYERS.add(_raw_name)
                    CANONICAL_HALL_OF_FAME_PLAYERS.add(_raw_name.replace(".", "").replace("-", " "))
                    _teams = _ind.get("teams", [])
                    if _teams:
                        if _raw_name not in CANONICAL_FRANCHISE_MAP:
                            CANONICAL_FRANCHISE_MAP[_raw_name] = []
                        for _t in _teams:
                            if _t not in CANONICAL_FRANCHISE_MAP[_raw_name]:
                                CANONICAL_FRANCHISE_MAP[_raw_name].append(_t)
    except Exception:
        pass

# ---------------------------------------------------------------------------
# College Map — player name (lowercase) → college
# ---------------------------------------------------------------------------
CANONICAL_COLLEGE_MAP: Dict[str, str] = {
    "travis hunter": "Colorado",
    "shedeur sanders": "Colorado",
    "cam ward": "Miami",
    "abdul carter": "Penn State",
    "ashton jeanty": "Boise State",
    "arch manning": "Texas",
    "nico iamaleava": "Tennessee",
    "jeremiah smith": "Ohio State",
    "ryan williams": "Alabama",
    "caleb williams": "USC",
    "jayden daniels": "LSU",
    "drake maye": "North Carolina",
    "marvin harrison jr": "Ohio State",
    "joe alt": "Notre Dame",
    "malik nabers": "LSU",
    "jc latham": "Alabama",
    "michael penix jr": "Washington",
    "rome odunze": "Washington",
    "jj mccarthy": "Michigan",
    "j.j. mccarthy": "Michigan",
    "olu fashanu": "Penn State",
    "bo nix": "Oregon",
    "brock bowers": "Georgia",
    "jordan morgan": "Arizona",
    "dallas turner": "Alabama",
    "xavier worthy": "Texas",
    "bijan robinson": "Texas",
    "quinshon judkins": "Ole Miss",
    "omarion hampton": "North Carolina",
    "kaleb johnson": "Iowa",
    "ashton jeanty": "Boise State",
    "will campbell": "LSU",
    "mason graham": "Michigan",
    "jack sawyer": "Ohio State",
    "james pearce jr": "Tennessee",
    "tyler booker": "Alabama",
    "colston loveland": "Michigan",
    "tetairoa mcmillan": "Arizona",
}

# ---------------------------------------------------------------------------
# Known fallback players (for KNOWN_FALLBACK_PLAYERS dict)
# ---------------------------------------------------------------------------
KNOWN_FALLBACK_PLAYERS: Dict[str, Dict[str, Any]] = {
    # 2024 Draft
    "draft2024-williams-cal01": {"name": "Caleb Williams", "position": "QB", "startYear": 2024, "draft_round": 1},
    "draft2024-daniels-jay01": {"name": "Jayden Daniels", "position": "QB", "startYear": 2024, "draft_round": 1},
    "draft2024-maye-dra01": {"name": "Drake Maye", "position": "QB", "startYear": 2024, "draft_round": 1},
    "draft2024-harrison-mar01": {"name": "Marvin Harrison Jr.", "position": "WR", "startYear": 2024, "draft_round": 1},
    "draft2024-alt-joe01": {"name": "Joe Alt", "position": "OT", "startYear": 2024, "draft_round": 1},
    "draft2024-nabers-mal01": {"name": "Malik Nabers", "position": "WR", "startYear": 2024, "draft_round": 1},
    "draft2024-latham-jc01": {"name": "JC Latham", "position": "OT", "startYear": 2024, "draft_round": 1},
    "draft2024-penix-mic01": {"name": "Michael Penix Jr.", "position": "QB", "startYear": 2024, "draft_round": 1},
    "draft2024-odunze-rom01": {"name": "Rome Odunze", "position": "WR", "startYear": 2024, "draft_round": 1},
    "draft2024-mccarthy-jj01": {"name": "J.J. McCarthy", "position": "QB", "startYear": 2024, "draft_round": 1},
    "draft2024-fashanu-olu01": {"name": "Olu Fashanu", "position": "OT", "startYear": 2024, "draft_round": 1},
    "draft2024-nix-bo01": {"name": "Bo Nix", "position": "QB", "startYear": 2024, "draft_round": 1},
    "draft2024-bowers-bro01": {"name": "Brock Bowers", "position": "TE", "startYear": 2024, "draft_round": 1},
    "draft2024-fuaga-tal01": {"name": "Taliese Fuaga", "position": "OT", "startYear": 2024, "draft_round": 1},
    "draft2024-latu-lai01": {"name": "Laiatu Latu", "position": "DE", "startYear": 2024, "draft_round": 1},
    "draft2024-murphy-byr01": {"name": "Byron Murphy II", "position": "DT", "startYear": 2024, "draft_round": 1},
    "draft2024-turner-dal01": {"name": "Dallas Turner", "position": "LB", "startYear": 2024, "draft_round": 1},
    "draft2024-mims-ama01": {"name": "Amarius Mims", "position": "OT", "startYear": 2024, "draft_round": 1},
    "draft2024-verse-jar01": {"name": "Jared Verse", "position": "DE", "startYear": 2024, "draft_round": 1},
    "draft2024-fautanu-tro01": {"name": "Troy Fautanu", "position": "OT", "startYear": 2024, "draft_round": 1},
    "draft2024-robinson-cho01": {"name": "Chop Robinson", "position": "DE", "startYear": 2024, "draft_round": 1},
    "draft2024-mitchell-qui01": {"name": "Quinyon Mitchell", "position": "CB", "startYear": 2024, "draft_round": 1},
    "draft2024-thomas-bri01": {"name": "Brian Thomas Jr.", "position": "WR", "startYear": 2024, "draft_round": 1},
    "draft2024-arnold-ter01": {"name": "Terrion Arnold", "position": "CB", "startYear": 2024, "draft_round": 1},
    "draft2024-morgan-jor01": {"name": "Jordan Morgan", "position": "OT", "startYear": 2024, "draft_round": 1},
    "draft2024-barton-gra01": {"name": "Graham Barton", "position": "C", "startYear": 2024, "draft_round": 1},
    "draft2024-robinson-dar01": {"name": "Darius Robinson", "position": "DE", "startYear": 2024, "draft_round": 1},
    "draft2024-worthy-xav01": {"name": "Xavier Worthy", "position": "WR", "startYear": 2024, "draft_round": 1},
    "draft2024-guyton-tyl01": {"name": "Tyler Guyton", "position": "OT", "startYear": 2024, "draft_round": 1},
    "draft2024-wiggins-nat01": {"name": "Nate Wiggins", "position": "CB", "startYear": 2024, "draft_round": 1},
    "draft2024-pearsall-ric01": {"name": "Ricky Pearsall", "position": "WR", "startYear": 2024, "draft_round": 1},
    "draft2024-legette-xav01": {"name": "Xavier Legette", "position": "WR", "startYear": 2024, "draft_round": 1},

    # 2025 Draft
    "draft2025-ward-cam01": {"name": "Cam Ward", "position": "QB", "startYear": 2025, "draft_round": 1},
    "draft2025-hunter-tra01": {"name": "Travis Hunter", "position": "CB", "startYear": 2025, "draft_round": 1},
    "draft2025-sanders-she01": {"name": "Shedeur Sanders", "position": "QB", "startYear": 2025, "draft_round": 1},
    "draft2025-carter-abd01": {"name": "Abdul Carter", "position": "LB", "startYear": 2025, "draft_round": 1},
    "draft2025-jeanty-ash01": {"name": "Ashton Jeanty", "position": "RB", "startYear": 2025, "draft_round": 1},
    "draft2025-mcmillan-tet01": {"name": "Tetairoa McMillan", "position": "WR", "startYear": 2025, "draft_round": 1},
    "draft2025-graham-mas01": {"name": "Mason Graham", "position": "DT", "startYear": 2025, "draft_round": 1},
    "draft2025-campbell-wil01": {"name": "Will Campbell", "position": "OT", "startYear": 2025, "draft_round": 1},
    "draft2025-starks-mal01": {"name": "Malaki Starks", "position": "S", "startYear": 2025, "draft_round": 1},
    "draft2025-banks-kel01": {"name": "Kelvin Banks Jr.", "position": "OT", "startYear": 2025, "draft_round": 1},
    "draft2025-pearce-jam01": {"name": "James Pearce Jr.", "position": "DE", "startYear": 2025, "draft_round": 1},
    "draft2025-booker-tyl01": {"name": "Tyler Booker", "position": "OG", "startYear": 2025, "draft_round": 1},
    "draft2025-burden-lut01": {"name": "Luther Burden III", "position": "WR", "startYear": 2025, "draft_round": 1},
    "draft2025-loveland-col01": {"name": "Colston Loveland", "position": "TE", "startYear": 2025, "draft_round": 1},
    "draft2025-williams-myk01": {"name": "Mykel Williams", "position": "DE", "startYear": 2025, "draft_round": 1},
    "draft2025-revel-sha01": {"name": "Shavon Revel Jr.", "position": "CB", "startYear": 2025, "draft_round": 1},
    "draft2025-walker-jal01": {"name": "Jalon Walker", "position": "LB", "startYear": 2025, "draft_round": 1},
    "draft2025-grant-ken01": {"name": "Kenneth Grant", "position": "DT", "startYear": 2025, "draft_round": 1},
    "draft2025-scourton-nic01": {"name": "Nic Scourton", "position": "DE", "startYear": 2025, "draft_round": 1},
    "draft2025-milroe-jal01": {"name": "Jalen Milroe", "position": "QB", "startYear": 2025, "draft_round": 1},
    "draft2025-ewers-qui01": {"name": "Quinn Ewers", "position": "QB", "startYear": 2025, "draft_round": 1},
    "draft2025-dart-jax01": {"name": "Jaxson Dart", "position": "QB", "startYear": 2025, "draft_round": 1},
    "draft2025-egbuka-eme01": {"name": "Emeka Egbuka", "position": "WR", "startYear": 2025, "draft_round": 1},
    "draft2025-bond-isa01": {"name": "Isaiah Bond", "position": "WR", "startYear": 2025, "draft_round": 1},
    "draft2025-henderson-tre01": {"name": "TreVeyon Henderson", "position": "RB", "startYear": 2025, "draft_round": 1},
    "draft2025-judkins-qui01": {"name": "Quinshon Judkins", "position": "RB", "startYear": 2025, "draft_round": 1},
    "draft2025-morrison-ben01": {"name": "Benjamin Morrison", "position": "CB", "startYear": 2025, "draft_round": 1},
    "draft2025-johnson-wil01": {"name": "Will Johnson", "position": "CB", "startYear": 2025, "draft_round": 1},
    "draft2025-sawyer-jac01": {"name": "Jack Sawyer", "position": "DE", "startYear": 2025, "draft_round": 1},
    "draft2025-beck-car01": {"name": "Carson Beck", "position": "QB", "startYear": 2025, "draft_round": 1},
    "draft2025-warren-tyl01": {"name": "Tyler Warren", "position": "TE", "startYear": 2025, "draft_round": 1},
    "draft2025-hampton-oma01": {"name": "Omarion Hampton", "position": "RB", "startYear": 2025, "draft_round": 1},
    "draft2025-johnson-kal01": {"name": "Kaleb Johnson", "position": "RB", "startYear": 2025, "draft_round": 1},
    "draft2025-restrepo-xav01": {"name": "Xavier Restrepo", "position": "WR", "startYear": 2025, "draft_round": 1},
    "draft2025-skattebo-cam01": {"name": "Cam Skattebo", "position": "RB", "startYear": 2025, "draft_round": 1},

    # 2026 Draft
    "draft2026-manning-arc01": {"name": "Arch Manning", "position": "QB", "startYear": 2026, "draft_round": 1},
    "draft2026-iamaleava-nic01": {"name": "Nico Iamaleava", "position": "QB", "startYear": 2026, "draft_round": 1},
    "draft2026-smith-jer01": {"name": "Jeremiah Smith", "position": "WR", "startYear": 2026, "draft_round": 1},
    "draft2026-williams-rya01": {"name": "Ryan Williams", "position": "WR", "startYear": 2026, "draft_round": 1},
    "draft2026-stewart-dyl01": {"name": "Dylan Stewart", "position": "DE", "startYear": 2026, "draft_round": 1},
    "draft2026-seaton-jor01": {"name": "Jordan Seaton", "position": "OT", "startYear": 2026, "draft_round": 1},
    "draft2026-simmons-col01": {"name": "Colin Simmons", "position": "DE", "startYear": 2026, "draft_round": 1},
    "draft2026-robinson-ell01": {"name": "Ellis Robinson IV", "position": "CB", "startYear": 2026, "draft_round": 1},
    "draft2026-nussmeier-gar01": {"name": "Garrett Nussmeier", "position": "QB", "startYear": 2026, "draft_round": 1},
    "draft2026-branch-zac01": {"name": "Zachariah Branch", "position": "WR", "startYear": 2026, "draft_round": 1},
    "draft2026-downs-cal01": {"name": "Caleb Downs", "position": "S", "startYear": 2026, "draft_round": 1},
    "draft2026-wilson-eug01": {"name": "Eugene Wilson III", "position": "WR", "startYear": 2026, "draft_round": 1},
    "draft2026-woods-pet01": {"name": "Peter Woods", "position": "DT", "startYear": 2026, "draft_round": 1},
    "draft2026-mauigoa-fra01": {"name": "Francis Mauigoa", "position": "OT", "startYear": 2026, "draft_round": 1},
    "draft2026-proctor-kad01": {"name": "Kadyn Proctor", "position": "OT", "startYear": 2026, "draft_round": 1},
    "draft2026-lagway-dj01": {"name": "DJ Lagway", "position": "QB", "startYear": 2026, "draft_round": 1},
    "draft2026-hill-ant01": {"name": "Anthony Hill Jr.", "position": "LB", "startYear": 2026, "draft_round": 1},
    "draft2026-tate-car01": {"name": "Carnell Tate", "position": "WR", "startYear": 2026, "draft_round": 1},
}
